apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: vs-tea
  namespace: default
  labels:
    f5cr: "true"
spec:
  host: cafe.1broken.net
  hostGroup: "cafe"
  virtualServerAddress: "10.192.75.121"
  virtualServerHTTPPort: 443
  tlsProfileName: reencrypt-cafe
  httpTraffic: redirect
  snat: auto
  pools:
  - monitor:
      interval: 20
      recv: ""
      send: "GET /tea HTTP/1.1\r\nHost: cafe.1broken.net\r\n"
      timeout: 10
      type: https
    path: /tea
    service: tea-svc
    servicePort: 443