apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: edns-mocha
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  domainName: mocha.1broken.net
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  - dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: /Common/east
    monitor:
      type: https
      send: "GET /mocha HTTP/1.1\r\nHost: mocha.1broken.net\r\n"
      recv: ""
      interval: 10
      timeout: 30